services:
  stats-server:
    build: ./stats-service
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - TZ=Europe/Moscow


  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - TZ=Europe/Moscow

  ewm-service:
    build: ./main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-db
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - STATS_SERVER_URL=http://stats-server:9090
      - TZ=Europe/Moscow

  ewm-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - TZ=Europe/Moscow
